extract_geometry:

	make -f makefile.extract_geometry

extract_geometry_cube:

	make -f makefile.extract_geometry_cube

extract_geometry_stiffshell:

	make -f makefile.extract_geometry_stiffshell

extract_geometry_stiffcube:

	make -f makefile.extract_geometry_stiffcube

clean:

	rm *.o *.out
